nginx:
    image: tutum/nginx
    restart: always

    links:
        - phpfpm
    volumes:
        - ./nginx/default:/etc/nginx/sites-available/default
        - ./nginx/default:/etc/nginx/sites-enabled/default

        - ./logs/nginx-error.log:/var/log/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log

    ports:
        - "80:80"
        
    environment:
        - VIRTUAL_HOST=sisglobal.local,www.sisglobal.local,localhost

phpfpm:
    image: php:7-fpm
    restart: always
    ports:
        - "9000:9000"
    volumes:
        - ./public:/usr/share/nginx/html

mysql:
    image: mysql:latest
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: admin
    ports:
        - "3306:3306" 
